Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: app.lambda_handler
      CodeUri: /Users/mito/PycharmProjects/techstock_ranking_get_ranking/get_ranking
      Runtime: python3.9
      Architectures:
        - x86_64